### ISSUE TITLE
If no updates are necessary for a topic, the tool is silent

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/kafka-configurator#11]
Should we be more explicit and say "topicName: no updates necessary" or similar?

We could put a log in [this else branch](https://github.com/sky-uk/kafka-configurator/blob/master/src/main/scala/com/sky/kafka/configurator/TopicConfigurator.scala#L47), but I realise there's the potential for multiple logs depending on the outcome of `updatePartitionsIfDifferent()` and `updateConfigIfDifferent()`.

One to discuss, I'm sure there's arguments for and against.

**Comment by lacarvalho91** [comment]
Since the changes from #17 we will see log output such as:
```
“Replication factor unchanged for ${newTopic.name}.
“No change in number of partitions for ${newTopic.name}”
“No change in config for ${newTopic.name}”
```
