### ISSUE TITLE
Update README file with download instructions

### ISSUE THREAD

**Issue by paoloambrosio-skyuk** [sky-uk/kafka-configurator#8]
Now that we have a released version, we should add that information the `README.md` as well as a download badge for Bintray: [![Bintray](https://img.shields.io/bintray/v/sky-uk/oss-maven/kafka-configurator.svg)](https://bintray.com/sky-uk/oss-maven/kafka-configurator/).

**Comment by oliverlockwood** [comment]
This now addressed.
